### ISSUE TITLE
Automatically split the payload for log events based on the size of the payload

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-extensions/dt-extensions-python-sdk#17]
Current the max payload for log events is 1MB, soon to be 5MB.

We should automatically batch the log sending so that each call is under 5MB.

**Comment by j01am25** [comment]
We get a lot of errors like : code: 413 message: Payload must not be larger than 1048576 bytes
Would it be beneficial to implement split sending based on size, in addition to splitting by the number of lines?
