### ISSUE TITLE
Schema reference for activationSchema

### ISSUE THREAD

**Issue by sschmischke** [dynatrace-extensions/dt-extensions-python-sdk#31]
After uploading my first custom python extension I was faced with `Activation schema error` through Dynatrace Hub>Add extension UI. So I wanted to look at the activation schema reference but I can't find it at https://docs.dynatrace.com nor Extensions 2.0 API.

**Comment by dlopes7** [comment]
This is being done internally by a Dynatrace team, it is not part of the SDK documentation, but a settings 2.0 topic

**Comment by pitpalme** [comment]
Pardon me, for jumping in:

https://dynatrace-extensions.github.io/dt-extensions-python-sdk/guides/extension_structure.html#activation-schema

describes the existence of "Activation Schema", any documentation describing the details should be relevant to SDK documentation.
