### ISSUE TITLE
report_log_event does not send log message when using dt-extensions-sdk 1.1.15 

### ISSUE THREAD

**Issue by evaldasc** [dynatrace-extensions/dt-extensions-python-sdk#56]
when building extension with dt-extensions-sdk==1.1.15 `report_log_event` does not send log message

**To Reproduce**

- build with dt-extensions-sdk==1.1.15

below stops producing log message:

```python
self.report_log_event(
    item
    | self.core_dimensions
    | self.log_dimensions
    | endpoint["dimensions"]
)
```
**Expected behavior**
`report_log_event` reports log message

**Additional context**
item is a dict and all dimensions are dict's as well 
when extension rebuild with: `install_requires=["dt-extensions-sdk==1.1.14]"` log message is being sent again

**Comment by dlopes7** [comment]
There was a bug in 1.1.15 indeed, it has since been fixed
