### ISSUE TITLE
Extension returned non-zero exit status 3221225477 during stage 2 of building(assemble part)

### ISSUE THREAD

**Issue by Eirik-Brudal** [dynatrace-extensions/dt-extensions-python-sdk#78]
When I'm running dt-sdk build it returned non-zero exit status 3221225477 during Stage 2 of building, same happen if I just try dt-sdk assemble. It started after dt-sdk 1.2.1.
I used to have Python 3.12.4 since the dt-sdk requirements was 3.10 or newer, and everything worked until 1.2.1 when I got told I had to have Python 3.10.x and not >= 3.10. After downloading it this error started in all new virtual environment.
Tried multiple Python 3.10.x version and Pip version 24.1.1 and 21.2.3, all return same status during the assemble part.
Also tried running VSCode as admin, and still no changes.
Took a clean reinstallation of VSCode and Python, deleting every entry I could find under %appdata%, %programfiles%, in RegEdit, etc.
I have a Citrix Virtual Desktop with the exact same versions where it works fine.
If I open one of my old extensions it works fine, tested with one that has dt-sdk 1.1.14 and python 3.12.4. In the same extension I tried to create new environment on Friday with dt-sdk version 1.2.3 and Python 3.10.11, and it failed. Just as with completely new extensions.
Same happens also if I only have one Python version installed.
I have now Python 3.12.4 so I can work with my extensions in old venv with older dt-sdk, and 3.10.0 to try to create new.
Can't quite put my finger on where the problem are. Since it work on one machine and not the other with exact same versions, and also it still works with newer Python and old dt-sdk, but not recommended python and newer dt-sdk, even after clean reinstall.

![Skjermbilde 2024-07-01 093728](https://github.com/dynatrace-extensions/dt-extensions-python-sdk/assets/174120669/58421e80-a9c5-4ad1-9000-da7e9c80fa16)

**Comment by dlopes7** [comment]
Python `3.10.0` was release 3 years ago and several fixes were made since then.

Can you please report if the same happens with python `3.10.14` as I can't reproduce this?

**Comment by Eirik-Brudal** [comment]
Do it has to be 3.10.14? Because there are no windows installer for later than 3.10.11. But when tried on Friday with 3.10.11 and 3.10.10, i got the same message as I did when I tried 3.10.0 today on my picture.
Don't know if you are able to access ticket ID 342266 in Dynatrace support system, but i pasted the message from my 3.10.11 attempt there.
 
![image](https://github.com/dynatrace-extensions/dt-extensions-python-sdk/assets/174120669/31bec42b-bb25-441d-8755-4a8d92975c03)

**Comment by Eirik-Brudal** [comment]
Was not able to find out how to install python 3.10.14 from the tarball, but i tried with 3.10.11 from C:\tmp folder i made. And same result.
I think it's gonna be easier to just install a new VDI since I dont got much, and not sure what settings i have managed to break.
