### ISSUE TITLE
add support for Unit in the report_metric method

### ISSUE THREAD

**Issue by Tommy-TI** [dynatrace-extensions/dt-extensions-python-sdk#92]
**Is your feature request related to a problem? Please describe.**
not a problem since we can update it in the Dynatrace console after ingest

**Describe the solution you'd like**
I would like to be able to specify the unit of the metric directly in the code in the method report_metric.

**Describe alternatives you've considered**
Update it in the console.

**Comment by dlopes7** [comment]
This can be done in the extension.yaml file metrics section, or by manually reporting mint lines with metadata comments
