### ISSUE TITLE
Report metric fails on '\' character

### ISSUE THREAD

**Issue by ThibaultLesuisse** [dynatrace-extensions/dt-extensions-python-sdk#93]
**Describe the bug**
We have a custom extension V2 in python that performs some healthcheck. It should report back the metrics to Dynatrace with the status and the url used to perform the healthcheck. Our call looks this:

``` python
self.report_metric(
    key="healthcheck_state",
    value="success",
    dimensions={"url": "google.be"}
)
```

When checking the logs on the Active Gate we get the following error back:

```
Error HTTP 400 from http://127.0.0.1:14599/mint/8460131254161511808: b'{\n    "error": {\n        "invalidLines": [\n            {\n                "line": 1,\n                "error": "invalid metric field in message \'healthcheck_state,url=\\"google.com\\" gauge,success 1732025455011\'; error at \' \'  (index 48)"\n            },\n            {\n                "line": 2,\n                "error": "invalid metric field in message \'healthcheck_state,url=\\"google.com\\" gauge,success 1732025455011\'; error at \' \'  (index 48)"\n            }\n        ],\n        "code": 400,\n        "message": "2 invalid lines"\n    },\n    "linesOk": 0,\n    "linesInvalid": 2\n}'

```

I guess this means that the validation of the metric fails. After reading about the MINT protocol I still wonder why it fails? I don't see a ```\``` somewhere. Seems to me like the ```dict``` is not correctly serialized and the quotes are escaped? Can this be avoided? 

Could it be related to this [line ](https://github.com/dynatrace-extensions/dt-extensions-python-sdk/blob/88e01af748b7e8a0357b000fd2a6320e6040f105/dynatrace_extension/sdk/metric.py#L87)

```python
def _key_and_dimensions(self):
    if not self.dimensions:
        return f"{self.key}"

    # Double quotes are added around {v} but later escaped.
    dimensions_string = ",".join([f'{k}="{v}"' for k, v in self.dimensions.items()])
    return f"{self.key},{dimensions_string}"
```

**To Reproduce**
1. Write a custom V2 extension in python
2. Report a metric
3. Check AG logs

**Expected behavior**
Metric is correctly reported

**Comment by dlopes7** [comment]
The word "success" is not a number, please see the [MINT protocol](https://docs.dynatrace.com/docs/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-ingestion-protocol)

If you want to report the `success` status report a metric with value `1` and `success` as the value of a dimension called `status` or something like that

**Comment by ThibaultLesuisse** [comment]
Does it have to be a number? Then why accept string values as values?

```python
self.value: Union[float, int, str, SummaryStat] = value
```

**Comment by ThibaultLesuisse** [comment]
Make sense though! Even though it might sound stupid you should consider adding it to the docs.

Thanks for the quick response anyway!

**Comment by dlopes7** [comment]
Good point, we can improve SDK and dynatrace docs on that
